
server:
  port: 8761

spring:
  application:
    name: mcs-discovery
  security:
    user:
      name: root
      password: ccmanager
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

eureka:
  server:
    #enable-self-preservation: false
  instance:
    hostname: mcs-discovery
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      #defaultZone: http://root:ccmanager@localhost:8761/eureka/
      defaultZone: http://root:ccmanager@${eureka.instance.hostname}:${server.port}/eureka/

logging:
  level:
    org:
      springframework:
        security: DEBUG
    com:
      netflix:
        eureka: OFF
        discovery: OFF


management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: /discovery-mgmt
    jmx:
      exposure:
        exclude:
          - '*'
  endpoint:
    health:
      enabled: true
      show-details: ALWAYS
    info:
      enabled: true