

spring:
  application:
    name: corona-tracker

server:
  port: 6070
  servlet:
    context-path: /corona-tracker

eureka:
  client:
    serviceUrl:
      defaultZone: http://root:ccmanager@localhost:8761/eureka/

feign:
  client:
    corona-service:
      url: http://corona-service
    config:
      default:
        connectionTimeout: 160000000
        readTimeout: 160000000

logging:
  level:
    com:
      netflix: DEBUG
    org:
      springframework:
        cloud: DEBUG

ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000